language: node_js
node_js: '12'
cache: yarn
addons:
  code_climate:
    repo_token: 'your repo token'
  firefox: "69.0"
services:
  - xvfb
notifications:
  email: false
before_script:
  - npm install codeclimate-test-reporter
  - alias codeclimate="./node_modules/codeclimate-test-reporter/bin/codeclimate.js"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
